### ISSUE TITLE
Broken link to "Automatic Nested Paths" functionality guide

### ISSUE THREAD

**Issue by julealgon** [MicrosoftDocs/OData-docs#201]
In this page, https://docs.microsoft.com/en-us/odata/webapi/nested-paths-routing, the link presented in the article points to a 404.

The correct link should probably be this one:
- https://docs.microsoft.com/en-us/odata/webapi/automatic-nested-paths-with-enable-nested-paths

**Comment by xuzhg** [comment]
@julealgon Do you mind to share a PR for us?

**Comment by KenitoInc** [comment]
@julealgon I can't repro this issue. I assume it was fixed. Kindly confirm

**Comment by julealgon** [comment]
> @julealgon I can't repro this issue. I assume it was fixed. Kindly confirm

That does seem to be the case indeed. Closing.
