### ISSUE TITLE
Using OData client without auto-generated proxy classes.

### ISSUE THREAD

**Issue by habbes** [MicrosoftDocs/OData-docs#91]
All code samples in the OData Client docs  appear to use auto-generated proxy classes for the TripPin service. I was wondering why there are no examples showing how to use the barebones OData client library directly to interact with an existing OData service without using a tool or extension to pre-generate code. Is this not a valid or intended use case?

**Comment by marabooy** [comment]
https://docs.microsoft.com/en-us/odata/client/basic-crud-operations#using-with-pocos
